// Shared frame layout for the debug tileset spritesheet (public/assets/debug-tileset.png,
// generated by scripts/generateDebugTileset.mjs). Both the generator and this module
// agree on frame indices by convention, not by a shared import — the generator is a
// plain-node .mjs script that can't import TS source directly, so this file is the
// single source of truth documenting the raster order the generator MUST match
// (mirrored there in a short comment pointing back here).
//
// Layout (row-major, DEBUG_TILESET_COLS columns per row):
//   frame 0            floor            solid gray
//   frame 1            stairs-NS        horizontal lines (climbs north/south)
//   frame 2            stairs-EW        vertical lines (climbs east/west)
//   frame 3 .. 18       wall mask4 0..15  purple-gray + black 3px border per autotile.ts's edgesForMask4

export const DEBUG_TILE_PX = 48;
export const DEBUG_TILESET_COLS = 4;
export const DEBUG_TILESET_KEY = "debug-tileset";
export const DEBUG_TILESET_PATH = "assets/debug-tileset.png";

export const FRAME_FLOOR = 0;
export const FRAME_STAIRS_NS = 1;
export const FRAME_STAIRS_EW = 2;
/** Wall variant frame for cardinal mask4 (0..15) is WALL_FRAME_BASE + mask4. */
export const WALL_FRAME_BASE = 3;
export const DEBUG_TILESET_FRAME_COUNT = WALL_FRAME_BASE + 16;

/** The frame index for a given 4-bit cardinal wall mask (0..15). */
export function wallFrameFor(mask4: number): number {
  return WALL_FRAME_BASE + mask4;
}
