export {
  TERRAIN_KINDS,
  TERRAIN_SURFACES,
  TERRAIN_FEATURES,
  TERRAIN_PROPS,
  TERRAIN_HEIGHT_EPSILON,
  TERRAIN_FLOOR_EDGE_MIN_DROP,
  TERRAIN_CLIFFS,
  TERRAIN_PRESENTATION_MODES,
  OUTSIDE_TERRAIN_PRESENTATION,
  planTerrain,
  type TerrainBatches,
  type TerrainFloorQuad,
  type TerrainFeatureQuad,
  type TerrainFeatureKind,
  type TerrainPropQuad,
  type TerrainPropKind,
  type TerrainKind,
  type TerrainSurface,
  type TerrainPresentation,
  type TerrainPresentationMode,
  type TerrainPlan,
  type TerrainPlanOptions,
  type TerrainQuadVertices,
  type TerrainRect,
  type TerrainSouthFaceQuad,
  type TerrainVoidQuad,
  type TerrainSource,
  type TerrainVertex,
  type TerrainCliffEdgeQuad,
  type TerrainCliffKind,
  type TerrainCliffSide,
  type TerrainQuarterTurn,
  type TerrainAOQuad,
  type TerrainAOMask,
} from "./planning/terrainPlanner.js";

export {
  TERRAIN_ATLAS_COLUMNS,
  TERRAIN_ATLAS_ROWS_PER_SET,
  TERRAIN_TILE_ROLES,
  TERRAIN_TILESETS,
  terrainAtlasFrame,
  terrainAtlasFrameName,
  terrainFrameFor,
  terrainTileRoleIndex,
  type TerrainAtlasSet,
  type TerrainAtlasFrame,
  type TerrainTileRole,
} from "./planning/tileset.js";

export { TerrainRenderer } from "./runtime/renderer.js";
export type { TerrainRendererLike } from "./rendererPort.js";

export {
  TerrainAtlasBatchRenderer,
  installTerrainAtlasFrames,
  atlasDraws,
  terrainMeshBatches,
  type TerrainAtlasDraw,
  type TerrainAtlasRenderOptions,
  type TerrainMeshBatch,
} from "./batch/atlasBatch.js";
