export {
  TERRAIN4,
  TERRAIN4_FEATURES,
  TERRAIN4_PROPS,
  TERRAIN4_HEIGHT_EPSILON,
  TERRAIN4_FLOOR_EDGE_MIN_DROP,
  TERRAIN4_CLIFFS,
  planTerrain4,
  type Terrain4Batches,
  type Terrain4FloorQuad,
  type Terrain4FeatureQuad,
  type Terrain4FeatureKind,
  type Terrain4PropQuad,
  type Terrain4PropKind,
  type Terrain4Kind,
  type Terrain4Plan,
  type Terrain4PlanOptions,
  type Terrain4QuadVertices,
  type Terrain4Rect,
  type Terrain4SouthFaceQuad,
  type Terrain4VoidQuad,
  type Terrain4Source,
  type Terrain4Vertex,
  type Terrain4CliffEdgeQuad,
  type Terrain4CliffKind,
  type Terrain4CliffSide,
  type Terrain4QuarterTurn,
  type Terrain4AOQuad,
  type Terrain4AOMask,
} from "./planning/terrainPlanner.js";

export {
  TERRAIN4_ATLAS_COLUMNS,
  TERRAIN4_ATLAS_ROWS_PER_SET,
  TERRAIN4_TILE_ROLES,
  TERRAIN4_TILESETS,
  TERRAIN4_CLIFF_ROLES,
  TERRAIN4_CLIFF_TILESETS,
  terrain4AtlasFrame,
  terrain4AtlasFrameName,
  terrain4FrameFor,
  terrain4TileRoleIndex,
  type Terrain4AtlasSet,
  type Terrain4AtlasFrame,
  type Terrain4TileRole,
  type Terrain4CliffTileRole,
  type Terrain4CliffAtlasSet,
} from "./planning/terrain4Tileset.js";

export { Terrain4Renderer, type TerrainRendererLike } from "./runtime/terrain4Renderer.js";

export {
  Phaser4TerrainAtlasBatchRenderer,
  installTerrain4AtlasFrames,
  terrain4AtlasDraws,
  terrain4MeshBatches,
  type Terrain4AtlasDraw,
  type Terrain4AtlasRenderOptions,
  type Terrain4MeshBatch,
} from "./batch/phaser4AtlasBatch.js";
